### ISSUE TITLE
Error trying to use in rails 5.0.0 app

### ISSUE THREAD

**Issue by mhfs** [fnando/babel-schmooze-sprockets#4]
Hi there,

I tried following your article (http://nandovieira.com/using-es2015-with-asset-pipeline-on-ruby-on-rails) with a fresh rails 5.0.0 app and got into the error below.

I put a test app together at https://github.com/mhfs/es6test in case it helps you reproduce.

I apologize in advance in case it's not related to this gem. I'm not a big expert in the asset-pipeline ecosystem.

Let me know if I can help with anything else.

```
Unknown plugin "external-helpers" specified in "base" at 0, attempted to resolve relative to "/Users/mhfs/Code/tmp/es6test/app/assets/javascripts"

Extracted source (around line #2):
1 //= link_tree ../images
2 //= link_directory ../javascripts .js
3 //= link_directory ../stylesheets .css

Backtrace:
app/assets/config/manifest.js:2
schmooze (0.1.6) lib/schmooze/base.rb:117:in `call_js_method'
schmooze (0.1.6) lib/schmooze/base.rb:28:in `block in method'
babel-schmooze-sprockets (0.1.3) lib/babel-schmooze-sprockets/babel_processor.rb:64:in `block in call'
sprockets (4.0.0.beta2) lib/sprockets/cache.rb:85:in `fetch'
babel-schmooze-sprockets (0.1.3) lib/babel-schmooze-sprockets/babel_processor.rb:46:in `call'
babel-schmooze-sprockets (0.1.3) lib/babel-schmooze-sprockets/babel_processor.rb:29:in `call'
sprockets (4.0.0.beta2) lib/sprockets/processor_utils.rb:83:in `call_processor'
...
```

**Comment by mhfs** [comment]
Also:

```
➜  es6test $ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
➜  es6test $ node -v
v6.3.0
➜  es6test $ npm -v
3.10.3
```

Tests for this gem passes locally.

**Comment by bingxie** [comment]
Same issue.

**Comment by dcmorse** [comment]
Same issue. Rails 4.x

**Comment by ike** [comment]
Same here! Looking into possibilities.

**Comment by dcmorse** [comment]
Looking at the github activity, it looks like `babel-schmooze-sprockets` has been dark for about a month now. 

For what it's worth I also tried following the instructions at https://babeljs.io/docs/setup/#installation, and it worked for me.

**Comment by gnumarcelo** [comment]
Does anyone got a fix for this?

**Comment by codeclown** [comment]
I landed here from Google, and have no idea what Schmooze or Sprockets is, but for the record, this error is simply due to missing a dependency.

```
npm install babel-plugin-external-helpers
```
